// Holodex API documentation is not reflective of the actual fields
// So this is a best-effort "documentation" of the real API

export type Channel = {
	id: string;
	name: string;
	org?: string;
	/**
	 * Always prefixed by two characters used strictly for sorting,
	 * don't forget to strip those before displaying
	 */
	suborg?: string;
	type: 'vtuber' | 'subber';
	/**
	 * CDN URL to profile picture
	 */
	photo: string;
	/**
	 * Note that even when this field exists in the API response,
	 * it can be the empty string and should not be used in that case
	 */
	english_name?: string;
	lang?: string | null;
};

export type AnnotatedChannel = Channel & {
	/**
	 * Identical to `suborg` without the two character sorting prefix
	 */
	group: string;
	/**
	 * The service presently known as X dot com
	 */
	twitter: string;
	video_count: number;
	subscriber_count: number;
	clip_count: null | number;
	top_topics: string[];
	/**
	 * This is kind of an internal field that just controls the rate at which holodex checks the channel
	 * and is not *really* equivalent to graduation/termination/affiliation
	 */
	inactive: boolean;
	twitch: null | string;
	/**
	 * Used to reattribute autogenerated Topic channels to main channel
	 */
	extra_ids: null | string[];
};

type BaseStreamEntry = {
	id: string;
	title: string;
	type: 'stream';
	topic_id?: string;
	published_at: string;
	available_at: string;
	/**
	 * How long the stream was in seconds
	 */
	duration: number;
	channel: Channel;
	mentions?: Channel[];
};

export type UpcomingStream = BaseStreamEntry & {
	status: 'upcoming';
	available_at: string;
	live_viewers?: 0;
	start_actual?: never;
};

export type LiveStream = BaseStreamEntry & {
	status: 'live';
	start_scheduled: string;
	start_actual: string;
	live_viewers: number;
};

export type MissingStream = BaseStreamEntry & {
	status: 'missing';
	live_viewers?: number;
	start_scheduled?: string;
	start_actual?: never;
};

export type PastStream = BaseStreamEntry & {
	status: 'past';
	published_at: string;
	songcount?: number;
};

export type StreamEntry = UpcomingStream | LiveStream | MissingStream | PastStream;
export type ValidSearchReponse = { total: number; items: StreamEntry[] };
export type ErrorSearchResponse = { message: string };
export type SearchReponse = ValidSearchReponse | ErrorSearchResponse;
